export const EngErrorMessageConstant = {
  imageIsNotNull: 'Image is not null.',
  logoIsNotNull: 'Logo is not null.',
  NotExistEmail: 'Email does not exist in the system.',
  AlreadyExistEmail: 'Email already exists in the system.',
  AlreadyExistCitizenNumber: 'Citizen number already exists in the system.',
  InvalidKitchenCenterId: 'Kitchen center id is not suitable id in the system.',
  InvalidBrandId: 'Brand id is not suitable id in the system.',
  InvalidStoreId: 'Store id is not suitable id in the system.',
  InvalidCategoryId: 'Category id is not suitable id in the system.',
  InvalidBankingAccountId: 'Banking account id is not suitable id in the system.',
  InvalidCashierId: 'Cashier id is not suitable id in the system.',
  InvalidProductId: 'Product id is not suitable id in the system.',
  NotExistKitchenCenterId: 'Kitchen center id does not exist in the system.',
  NotExistKitchenCenter: 'Kitchen center does not exist in the system.',
  NotExistBrandId: 'Brand id does not exist in the system.',
  NotExistStoreId: 'Store id does not exist in the system.',
  NotExistCategoryId: 'Category id does not exist in the system.',
  NotExistBankingAccountId: 'Banking account id does not exist in the system.',
  NotExistProductId: 'Product id does not exist in the system.',
  NotExistCashierId: 'Cashier id does not exist in the system.',
  InvalidItemsPerPage: 'Items per page number is required more than 0.',
  InvalidCurrentPage: 'Current page number is required more than 0.',
  NotExistPartnerId: 'Partner id does not exist in the system.',
  NotExistAccountId: 'Account id does not exist in the system.',
  InvalidPartnerId: 'Partner id is not suitable id in the system.',
  CategoryIdNotBelongToBrand: 'Category id does not belong to your brand.',
  CategoryIdNotBelongToStore: 'Category id does not belong to your store.',
  AlreadyExistPartnerProduct: 'Mapping product already exists in the system.',
  NotExistPartnerProduct: 'Mapping priduct does not exist in the system.',

  DisabledAccount: 'Account has been disabled.',
  InvalidEmailOrPassword: 'Email or Password is invalid.',

  AccountIdNotBelongYourAccount: 'Account id does not belong to your account.',

  NotAuthenticatedEmailBefore: 'Email has not been previously authenticated.',
  ExpiredOTPCode: 'OTP code has expired.',
  NotMatchOTPCode: 'Your OTP code does not match the previously sent OTP code.',

  InvalidAccessToken: 'Access token is invalid.',
  NotExpiredAccessToken: 'Access token has not yet expired.',
  NotExistAuthenticationToken: 'You do not have the authentication tokens in the system.',
  NotExistRefreshToken: 'Refresh token does not exist in the system.',
  NotMatchAccessToken: 'Your access token does not match the registered access token.',
  ExpiredRefreshToken: 'Refresh token expired.',

  NotAuthenticatedEmail: 'Email has not been previously authenticated.',
  NotVerifiedEmail: 'Email is not yet authenticated with the previously sent OTP code.',

  DeactiveKitchenCenter_Update: 'Kitchen center was deleted before, so this kitchen center cannot update.',
  DeactiveKitchenCenter_Delete: 'Kitchen center cannot delete because that was deleted before.',
  KitchenCenterManagerEmailExisted: 'Kitchen center manager email already existed in the system.',
  ExistedActiveStores_Delete: 'The kitchen center has active stores, so this kitchen center cannot be deleted.',
  NotBelongToKitchenCenter: 'Kitchen center id does not belong to your kitchen center.',

  InvalidStatusFilter: 'Key status filter is required ACTIVE, INACTIVE in the system.',
  NotBelongToBrand: 'Brand id does not belong to your brand.',
  DeactiveBrand_Delete: 'Brand cannot delete because that was deleted before.',
  DeactiveBrand_Update: 'Brand was deleted before, so this brand cannot update.',
  BrandManagerEmailExisted: 'Brand manager email already existed in the system.',
  RoleNotSuitable: 'Role is not suitable',
  ProductNotBelongToBrand: 'This product not belong to brand.',
  KeySortNotExist: 'Key sort are ASC or DESC',

  BrandNotJoinKitchenCenter: 'Brand does not join into the kitchen center.',
  KitchenCenterNotHaveBrand: 'Kitchen center does not have this brand.',
  BrandNotHaveStore: 'Brand does not have this store in the system.',
  KitchenCenterNotHaveStore: 'Kitchen center does not have this store in the system.',
  DeactiveStore_Update: 'Store was deleted before, so this store cannot update.',
  DeactiveStore_Delete: 'Store cannot delete because that was deleted before.',
  ManageremailExisted: 'Store manager email already existed in the system.',
  NotConfirmingStore: 'Store is not a new store to confirm to become an ACTIVE store.',
  NotRejectedResonForNewStore: 'Rejected store registration is required a reason.',
  StoreIdNotBelongToStore: 'Store id does not belong to your store.',
  StoresWithStatusNameParam: 'Status is required some type such as: Active, Inactive, Rejected, Be comfirming.',

  CategoryCodeExisted: 'Category code already exist in the system.',
  DeactiveCategory_Delete: 'Category cannot delete because that was deleted before.',
  DeactiveCategory_Update: 'Category was deleted before, so this category cannot update.',
  InvalidCategoryType: 'Type is required.',
  NotExistCategoryType: 'Type is required NORMAL or EXTRA.',
  StatusInvalid: 'Status is ACTIVE or INACTIVE.',
  CategoryMustBeNormal: 'CategoryId must be a NORMAL type.',
  ExtraCategoryGreaterThan0: 'Extra category Id must be greater than 0.',
  ListExtraCategoryIdIsExtraType: 'List extra category Id need to be a EXTRA type.',
  ListExtraCategoryIdIsActive: 'List extra category Id need status is ACTIVE.',
  ExtraCategoryIdNotBelongToBrand: 'Extra category Id does not belong to brand.',
  ExtraCategoryIdDoesNotExist: 'Extra category Id does not exist in the system.',

  BankingAccountNotBelongToKitchenCenter: 'Your kitchen center does not have this banking account id.',
  NumberAccountExisted: 'Number account already existed in the system.',

  ProductCodeExisted: 'Code already exist in the system.',
  ParentProductIdNotExist: 'Parent product id does not exist in the system.',
  ParentProductIdNotBelongToBrand: 'Parent product id does not belong to your brand.',
  CategoryNotSuitableForSingleOrParentProductType:
    'Category id is not suitable type for SINGLE or PARENT product type.',
  CategoryNotSuitableForEXTRAProductType: 'Category id is not suitable type for EXTRA product type.',
  CategoryIdNotBelongToKitchenCenter: 'Your kitchen center cannot get products with this category id.',
  InvalidProductType: 'Product type is required some types such as: SINGLE, PARENT, CHILD, EXTRA.',
  ProductNotBelongToStore: 'Product id does not belong to your store.',
  ProductNotSpendToStore: 'Product id does not spend to your kitchen center.',
  ProductNameNotFollowingFormat:
    "Name of product Type CHILD is required following format: 'ParentName - Size x' With x is a your chosen size options.",
  ProductNameTypeChildNotAllowUpdate: 'Name of product which is type CHILD does not allow update.',
  ProductIdNotParentType: 'Product id is not a PARENT type.',

  DupplicatedPartnerName: 'Name already exist in the system.',
  DupplicatedWebUrl: 'Web Url already exist in the system.',
  DeactivePartner_Update: 'Partner was deleted before, so this partner cannot update.',
  DeactivePartner_Delete: 'Partner cannot delete because that was deleted before.',
  DeactivePartner_Get: 'Partner cannot get because that was deleted before.',
  PartnerHasPartnerStoreActive_Update: 'Partner can not update status because active stores is using this partner.',
  PartnerHasPartnerStoreActive_Delete: 'Partner can not delete status because active stores is using this partner.',

  CashierIdNotBelongToKitchenCenter: 'Cashier id does not belong to your kitchen center.',
  CashierIdNotBelogToCashier: 'Cashier id is not suitable with your account.',
  StatusIsRequiredWithKitchenCenterManager: 'Status is not null',
  StatusIsNotRequiredWithCashier: 'Cashier does not allow to update Status property.',

  InactiveStore_Create: 'This store has been inactive or disabled.',
  StoreNotBelongToBrand: 'Store does not belong to brand.',
  LinkedWithParner: 'This store is already linked to this partner.',
  UsernameExisted: 'Username already exist in the system.',
  NotLinkedWithParner: 'This store is not linked to this partner and it is still active.',
  DeactiveStorePartner_Update: "Can't update store partner has been deactivated.",
  DupplicatedPartnerId_Create: 'Partner Id cannot be duplicated in the partnerAccounts list.',
  GrabFoodAccountMustBeStoreManager: 'GrabFood Account must be Store Manager Role.',
  ItemOnGrabfoodCanNotMapping: 'The item on GrabFood cannot be mapped to any product in the MBKC System.',
  ModifierGroupOnGrabfoodCanNotMapping:
    'The modifier group on GrabFood cannot be mapped to any product in the MBKC System.',

  DeactiveProduct_Create_Update: 'This product is Deactive.',
  InactiveProduct_Create_Update: 'This product is Inactive.',
  InactiveStore_Update: 'This store has been inactive.',
  StatusInValid: 'Status is ACTIVE or INACTIVE',

  ProductCodeInPartnerNotExist: 'Product code does not exist in the GrabFood System.',
};
